name: Swift

on: 

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app && /usr/bin/xcodebuild -version
    - name: Resolve dependencies
      run: xcodebuild -resolvePackageDependencies
    - name: Run unit tests
      run: xcodebuild -resolvePackageDependencies test -scheme secant-testnet -project secant.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' | xcpretty && exit ${PIPESTATUS[0]}
